# Generated by Django 4.1.3 on 2023-01-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_categorywiseleaderboard_user_name_and_more'),
        ('tournament', '0003_remove_tournament_question_tournament_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='question',
            field=models.ManyToManyField(blank=True, to='question.question'),
        ),
    ]
