# Generated by Django 4.1.3 on 2023-01-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_categorywiseleaderboard_user_name_and_more'),
        ('tournament', '0004_tournament_category_tournament_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.category'),
        ),
    ]
