# Generated by Django 4.1.3 on 2023-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], default='Live', max_length=20),
        ),
    ]
