# Generated by Django 4.1.3 on 2023-01-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
    ]
