# Generated by Django 4.1.3 on 2023-01-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournamentquestion_tournamentquestionchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='question',
        ),
    ]
