# Generated by Django 4.1.3 on 2023-01-28 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0009_remove_tournament_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentWiseLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tour_point', models.IntegerField(blank=True, default='0', null=True)),
                ('user_name', models.CharField(default='User Name', max_length=255)),
            ],
            options={
                'verbose_name': 'TournamentWiseLeaderBoard',
                'verbose_name_plural': 'TournamentWiseLeaderBoards',
                'db_table': 'tournament_wise_leader_board',
            },
        ),
        migrations.CreateModel(
            name='StoreTournamentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField(default='0')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StoreTournamentAnswer',
                'verbose_name_plural': 'StoreTournamentAnswers',
                'db_table': 'store_tournament_answer',
            },
        ),
    ]
