# Generated by Django 4.1.3 on 2022-11-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
