# Generated by Django 4.1.3 on 2022-12-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_category_created_at_alter_question_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='storeanswer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='storeanswer',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeanswer',
            name='total',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_ans', models.CharField(max_length=700)),
                ('points', models.IntegerField(default='0')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.storeanswer')),
            ],
            options={
                'verbose_name': 'ParticipantAnswer',
                'verbose_name_plural': 'ParticipantAnswers',
                'db_table': 'participant_answer',
            },
        ),
    ]
