# Generated by Django 4.1.3 on 2022-12-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_storeanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantanswer',
            old_name='points',
            new_name='total_points',
        ),
        migrations.RenameField(
            model_name='storeanswer',
            old_name='total',
            new_name='point',
        ),
    ]
