# Generated by Django 4.1.3 on 2022-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_points_participantanswer_total_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWiseLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_point', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'CategoryWiseLeaderBoard',
                'verbose_name_plural': 'CategoryWiseLeaderBoards',
                'db_table': 'category_wise_leader_board',
            },
        ),
    ]
