# Generated by Django 4.1.3 on 2022-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_categorywiseleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorywiseleaderboard',
            name='user_name',
            field=models.CharField(default='User Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='categorywiseleaderboard',
            name='cat_point',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
